name: goodnight

on:

  workflow_dispatch:  # 允许手动触发测试

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send goodnight reminder
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install dependencies
        run: pip install -r ./requirements.txt

      - name: send message
        run: python ./main.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
